### ISSUE TITLE
PostGIS Operators possible?

### ISSUE THREAD

**Issue by lopsided** [jsor/doctrine-postgis#27] opened 2017-03-09 14:00 UTC
I've used this library to do a distance search (like a nearest-neighbour) and I had it with the query builder like:

````
        $res = $this->createQueryBuilder('l')
            ->addSelect('ST_Distance(l.point, :point) AS distance')
            ->orderBy('distance', 'asc')
            ->setMaxResults(1)
            ->setParameter('point', $point)
            ->getQuery()
            ->getOneOrNullResult();
````

But this was very slow, even though I had a spatial index on the point field. I came across an alternative way of doing it that is lightning fast:

````
$connection->executeQuery(
            'SELECT l.id
             FROM locations l 
             ORDER BY l.point <-> :point
             LIMIT 1',
            ['point' => $point]
````

But I can't get this to work in doctrine / DQL:

````
$this->createQueryBuilder('l')
            ->orderBy('l.point <-> :point')
            ->setMaxResults(1)
            ->setParameter('point', $point)
            ->getQuery()
            ->getOneOrNullResult();
````

As it complains about the operator ("<->")

````
[Doctrine\ORM\Query\QueryException]                                    
  [Syntax Error] line 0, col 65: Error: Expected end of string, got '<'  
````

Am I doing something wrong or is this just not supported? 

Many thanks for the excellent package!

http://postgis.net/docs/reference.html#Operators

**Comment by jsor** [comment] 2017-03-09 15:18
AFAICT, implementing custom operators isn't possible with Doctrine :(

**Comment by jsor** [comment] 2017-03-15 07:21
I don't think i can do much here. The only solution i'm aware of is using Doctrine's [Native SQL](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/native-sql.html) feature.

Closing for now. Feel free to reopen if you have further questions/ideas.

**Closed as completed by jsor** 2017-03-15 07:21 UTC

**Comment by EvanCarroll** [comment] 2017-11-24 23:43
Question on SO directed here.
https://stackoverflow.com/q/47476822/124486

**Comment by EvanCarroll** [comment] 2017-11-24 23:48
This should be closed as a dupe of https://github.com/jsor/doctrine-postgis/issues/15

**Comment by EvanCarroll** [comment] 2017-11-25 00:19
You may look at building atop of

* https://github.com/semin-lev/ltree-extension-bundle/blob/master/DqlFunction/LtreeOperatorFunction.php to meet these requests for operator support.

Also check out 

* https://blog.4xxi.com/using-custom-functions-in-symfony-doctrine-516496001945
* https://github.com/elnoro/doctrine-period-example
  * specific code example at https://github.com/elnoro/doctrine-period-example/blob/master/src/AppBundle/Doctrine/Query/OverlapsFunction.php (implementation of `&&` overlaps)

**Comment by jsor** [comment] 2017-11-25 10:17
Thanks for the links. The implementations are similar to what i proposed in https://github.com/jsor/doctrine-postgis/issues/15#issuecomment-240662356. I'm happy to accept a PR for that. :)
